### ISSUE TITLE
After passing the evaluator getting an error  : Must specify reference_key

### ISSUE THREAD

**Issue by ayushigithub12** [langchain-ai/langsmith-cookbook#131]
![image](https://github.com/langchain-ai/langsmith-cookbook/assets/95244946/f7aaeb59-566b-42be-99bc-eb0afa748e98)

**Comment by hwchase17** [comment]
this is occurring because you likely have a dataset with multiple output keys. due to this, the evaluator doesn't know which one to use as the ground truth - so you have to tell it! You can do this by specifying the reference_key in the runEvalConfig, so:

```
evaluation_config = RunEvalConfig(
   ...,
   reference_key="result",
)
```

**Comment by ayushigithub12** [comment]
I also tried this by specifying the reference_key still I was getting the same error, but in RetrievalQA when I did :
 return_source_documents = False,
![image](https://github.com/langchain-ai/langsmith-cookbook/assets/95244946/0728eefc-7e63-41b9-b65e-c8d14b4381a8)

The error was solved.
Is there any other way that I can get the source_documents and still not get this error

**Comment by hinthornw** [comment]
You can specify the `prediction_key` as well
