### ISSUE TITLE
How to add custom field in tracer

### ISSUE THREAD

**Issue by sagorhishab** [langchain-ai/langsmith-cookbook#136]
Hi,
I need to trace some fields outside of the chain.
Such as I have some post-processing steps after getting the response. I want to trace that information too. At present, I am logging it. 
Is there any way to add a new field in the tracer?

Thanks in advance.

**Comment by hinthornw** [comment]
To log your postprocessing logic as a part of the chain, you could compose the postprocessing logic as a final runnable step in the chain.

For instance if you have

```
some_chain = ...
def my_chatbot(query):
      response = some_chain.run("foo")
      final_response = "<div>" + response.strip()+ "</div>"
      return final_response
```

you could change it to this:

```
some_chain = ...

def postprocess(response):
     return "<div>" + response.strip()+ "</div>"
composed_chain = some_chain | postprocess
def my_chatbot(query):
      return composed_chain.invoke(query)
```

**Comment by sagorhishab** [comment]
Hello @hinthornw ,
thank you. 
I was thinking about outside of the chain for adding a custom field. 
I have a complex chain, and there are so many things happening right now. 
Although I have several logs I wanted to add more information in the langsmith tracer. 
I can see it's not that easy.
Thanks again for your suggestion.

**Comment by hinthornw** [comment]
@sagorhishab you can also use tags, metadata, and feedback depending on the type of field you're trying to add.
- Tags are string values. Easy to search
- Metadata are any key-value pairs. Also convenient for searching/grouping
- Feedback has a key and value. Like metadata but usually presented in a way that's used for analytics
