### ISSUE TITLE
Any way to get token counts when not using langchain calls?

### ISSUE THREAD

**Issue by spisupat** [langchain-ai/langsmith-cookbook#161]
Thanks for this great library! 
In my use case, I am using the `traceable` decorator with non-langchain LLM calls and it works great to track inputs, outputs & latency - but it doesn't currently count I/O tokens, is there a way to configure the tracer or metadata keys to enable this?

**Comment by hinthornw** [comment]
@spisupat - If it follows the openai schema, then we'll be able to count the tokens!
