### ISSUE TITLE
@traceable doesn't allow you to save data from a method

### ISSUE THREAD

**Issue by kevingyang** [langchain-ai/langsmith-cookbook#166]
if we're calling an LLM via an object's method, some of the important metadata we want to log is in the object's data, and not passed in as an argument directly. is there any support to logging that?

**Comment by hinthornw** [comment]
Yeah. https://docs.smith.langchain.com/cookbook/tracing-examples/traceable#configuring-traces

```
@traceable()
def foo():
   return ""

result = foo(
    langsmith_extra={
        "tags": ["another-tag"],
        "metadata": {"another-key": 1},
    },
)
```
