### ISSUE TITLE
run_on_dataset takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by darthShana** [langchain-ai/langsmith-cookbook#167]
As per the documentation, when i run 
`
run_on_dataset(
    dataset_name="<my_dataset_name>",
    llm_or_chain_factory=<llm or function constructing chain>,
    client=client,
    evaluation=evaluation_config,
    project_name="<the name to assign to this test project>",
)
`
where 
llm_or_chain_factory=is a function
It correctly passes the input examples to the function
However if
llm_or_chain_factory=create_object
and create_object is
`
def create_object() -> MyPredictor:
    predictor = MyPredictor()
    # Return the function that will be called on the next row
    return predictor.predict
`
It still seems to call create_object with the input arguments instead of using create_object as a "factory" so i get the error
`
Error Type: TypeError, Message: create_object() takes 0 positional arguments but 1 was given
`
because its passing in the input args into the facotry

**Comment by hinthornw** [comment]
If you call `create_object()` directly does it throw an error (specifically a typeerror?) We do a lot of checks to try to help wrap it for you but if there's an error when initializing we may think it expects the argument

**Comment by hinthornw** [comment]
Going to close as stale
