### ISSUE TITLE
Langsmith not work

### ISSUE THREAD

**Issue by dobahoang** [langchain-ai/langsmith-cookbook#168]
Hello development team, I have been using Langsmith for a while. It gives quite good results. However, some days, it does not send process logs to langsmith.

Do you know what the reason is, is there a way to fix it?Thank you

**Comment by hinthornw** [comment]
Hi @dobahoang thanks for your patience. We added a lot of new users to the platform while we were still doing a big infra upgrade, which caused some downtime. We hope that soon this type of thing won't be an issue

**Comment by hinthornw** [comment]
Going to close this for now, as everything should be stable again.
