### ISSUE TITLE
Using GPT4 instead of GPT3.5-turbo

### ISSUE THREAD

**Issue by leticiacechinel** [langchain-ai/langsmith-cookbook#172]
Hi, I am making some tests with langsmith. When I run the model I explicitly call chat GPT3.5-turbo (`ChatOpenAI(model="gpt-3.5-turbo", temperature=0)`) but in my open IA usage info (https://platform.openai.com/usage) it charges me in GPT-4, which is more expensive.

I noticed that the only evaluators that I could use with gpt 3.5 where "embedding_distance" and "string_distance".

Does anyone have had similar problem?

**Comment by hinthornw** [comment]
You can still use gpt-3.5-turbo in the evaluators! It just is less reliable. We ran some comparisons previously: https://blog.langchain.dev/how-correct-are-llm-evaluators/
