### ISSUE TITLE
ModuleNotFoundError: No module named 'langsmith.run_helpers'; 'langsmith' is not a package

### ISSUE THREAD

**Issue by Garand0o0** [langchain-ai/langsmith-cookbook#178]
When I run `from langsmith.run_helpers import traceable`  in `tracing_without_langchain.ipynb`, I get the error '`ModuleNotFoundError: No module named 'langsmith.run_helpers'; 'langsmith' is not a package`'. 

Is this a version issue with langsmith, or is it something else? My version of langsmith is 0.0.85. python is 3.9.

**Comment by hinthornw** [comment]
Do you have a `langsmith.py` file somewhere in your working directory?

**Comment by Garand0o0** [comment]
> Do you have a `langsmith.py` file somewhere in your working directory?

Thank you for your response. I don't have `langsmith.py`. How should I go about obtaining it?

**Comment by Garand0o0** [comment]
> Do you have a `langsmith.py` file somewhere in your working directory?
I'm just running `tracing-examples/traceable/tracing_without_langchain.ipynb`, and there's no `langsmith.py` in the traceable folder. Do I need to create this myself?

**Comment by hinthornw** [comment]
What does it show if you run

```
import langsmith
print(langsmith.__version__)
```

in your notebook then?

**Comment by Garand0o0** [comment]
> What does it show if you run
> 
> ```
> import langsmith
> print(langsmith.__version__)
> ```
> 
> in your notebook then?

Thank you. I made a basic mistake. I created a new `langsmith.py` in PyCharm to run the code, which I shouldn't have named `'langsmith`'.
