### ISSUE TITLE
How to log to multiple projects when using langchain ts?

### ISSUE THREAD

**Issue by lukasugar** [langchain-ai/langsmith-cookbook#189]
Afaik, we need to specify `LANGCHAIN_PROJECT` environment variable:
```
export LANGCHAIN_TRACING_V2=true
export LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
export LANGCHAIN_API_KEY="<your-api-key>"
export LANGCHAIN_PROJECT="my_project_name"
```

In typescript, is it possible to log to different projects? By setting the environment variable, it seems only is possible.

I'd like to have something like this:
```
// src/api/suggestion.ts
llm.call(...)// this calls LLM to make suggestions

// srtc/api/review.ts
llm.call(...) // this calls LLM to make some reviews

```

These two calls have different usage, use different model and have different prompts. Is it possible to log them into different projects?

**Comment by hinthornw** [comment]
We'd typically recommend using tags to distinguish calls, but yes it's possible. Just manually provide the tracer

```
const tracer = new LangChainTracer({projectName: "foo"});
await llm.invoke(..., {callbacks: [tracer]})
```

**Comment by lukasugar** [comment]
That’s awesome, thanks!
I guess that if I provide tracers manually I don’t need to specify the
environment variable for project?

I’m calling the llm with “call” instead of “invoke”, will adding the
callback work?

response = await llm.call(query);


Regarding tags, I’ve found these docs:
https://docs.smith.langchain.com/tracing/faq/customizing_trace_attributes#adding-metadata-and-tags-to-traces

Could you please provide an example for adding tag to the llm call, not the
entire chain?

**Comment by hinthornw** [comment]
To just tag a single run, you can initialize the llm with tags `new ChatOpenAI(... tags=["foo"])` 
You can still use call, though you'd have to pass it via the callbacks argument. You could also switch to use invoke
