### ISSUE TITLE
My traces aren't showing up in langsmith

### ISSUE THREAD

**Issue by ojipadeson** [langchain-ai/langsmith-cookbook#248]
I added environment variables to my code:
```
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"] = "<my_api>"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
unique_id = uuid4().hex[0:8]
os.environ["LANGCHAIN_PROJECT"] = f"Tracing Walkthrough - {unique_id}"
```
However, the results of the program are not visible on Langsmith

I'm running a langchain example of the open-source model [qwen](https://qwen.readthedocs.io/en/latest/framework/Langchain.html)

Is there something I'm missing?

**Comment by hinthornw** [comment]
Seems like this is resolved?

**Comment by dhanesh24g** [comment]
This happened with me too. If you are using Jupyter Notebook, just restart the Kernel & this issue should be resolved.
